builds:
  - skip: true
  # Instead we build using the docker file and steps below.
  # I left this here in case there's ever a reason to use it.

  # - ldflags:
  #     - -s -w -extldflags "-static" -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
  #   tags:
  #     - osusergo
  #     - netgo
  #     - static
  #   env:
  #     - CGO_ENABLED=0
  #   # targets:
  #   #   - linux_amd64_v3
  #   goos:
  #     - linux
  #   goarch:
  #     - amd64
  #   goamd64:
  #     - v3
  #   hooks:
  #     post: upx --ultra-brute "{{ .Path }}" && upx -vt "{{ .Path }}"

dockers:
  - # skip_push: "true"
    extra_files:
      - go.mod
      - go.sum
      - secinfo.go
      - streamers
    image_templates:
      - "ghcr.io/infosecstreams/secinfo:{{ .Tag }}"
      - "ghcr.io/infosecstreams/secinfo:latest"
