name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # default fetch-depth is insufficent to find previous coverage notes
          fetch-depth: 10

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: make test

      - uses: gwatts/go-coverage-action@v1
        id: coverage
        with:
          test-args: '["-v"]'
          coverage-threshold: 85

      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.html
